# Generated by Django 5.2 on 2026-06-23 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='joinin_date',
            new_name='joining_date',
        ),
    ]
